### ISSUE TITLE
iOS doesn't build with Firebase Core 2.0

### ISSUE THREAD

**Issue by amigoni** [adjust/titanium_sdk#14]
There seem to be some conflicts with Adjust and Firebase Core module. 
iOS
Adjust 4.14.0
SDK 7.4.2 or 7.5.0 
Firebase 2.0 

I have yet to test with android but strongly suspect it will be the same

**Comment by uerceg** [comment]
Hi @amigoni 

Sorry for a bit delayed answer. Is this still an issue for you or did it somehow get resolved in the meantime? If still there, does it also happen with our latest SDK release?

Cheers

**Comment by uerceg** [comment]
In case this issue still persists with our latest SDK version, please feel free to reopen this issue and provide us with updated info. Cheers!
