### ISSUE TITLE
iOS deferred deeplink through Appcenter not able to retrieve webpageURL 

### ISSUE THREAD

**Issue by ericpolkadoc** [adjust/titanium_sdk#16]
Hi,

I have created the following Deeplink in our ios app (generalized all the vars and urls)

`https://our.deeplink.url/?adj_t=abc123&adj_campaign=test-campaign&adj_adgroup=test-adgroup&adj_creative=test-creative&adj_redirect=https%3A%2F%2Finstall.appcenter.ms%2Forgs%2Four-app-at-appcenter&urlMatch=https://www.someurl.com/parameter`

I can get the deeplink to work after the app is installed, whether it is backgrounded or closed.  But I can't retrieve the wepageURL data when deferred linking when installed through Appcenter.

`{"UIApplicationLaunchOptionsUserActivityDictionaryKey":{"UIApplicationLaunchOptionsUserActivityKey":{"userInfo":{},"activityType":"NSUserActivityTypeBrowsingWeb","webpageURL":"https://our.deeplink.url/?adj_t=abc123&adj_campaign=test-campaign&adj_adgroup=test-adgroup&adj_creative=test-creative&adj_redirect=https%3A%2F%2Finstall.appcenter.ms%2Forgs%2Four-app-at-appcenter&urlMatch=https://www.someurl.com/parameter"}}}`

Any thoughts on what I might be doing wrong?

Note: trying to get Ti.App.getArguments() 100% crashes my app.  I've seen some Appc Jira tickets on it, but nothing has any explanations, they all just say "solved".  If you have any experience with Ti.App.getArguments() crashing apps, please let me know.

I have been testing using a Slack link, none of the other Ad Environments take me to my Appcenter install page, so I'm not sure what's happening there either.  If you have any suggestion on how to test Email, Adwords, that would be great.

Thanks!

**Comment by uerceg** [comment]
Hi @ericpolkadoc 

Sorry for a bit delayed response. Not sure I fully understood what are you testing. From what I understood, direct deep link scenario (where you click on link while your app is already installed on the device) works for you but deferred deep link scenario (where you click on our tracker URL, make an install and are supposed to get the link later in the app) doesn't?

**Comment by ericpolkadoc** [comment]
Hi,

Yes what you were understanding is correct. I've been able to better the situation by using the iOS Notes app instead of Slack to test on.  I can now see the tracker recognized consistently in the setAttributionCallback on an iphone device.  However, the setDeferredDeeplinkCallback is not being fired, which is what I would expect to see fired on install. 

Once the app is installed though, the setDeferredDeeplinkCallback is always fired.

Is there anything that might prevent the setDeferredDeeplinkCallback from being fired in this scenario?

Also, I have a few different iphones that I am testing with.  The first is working as expected, but the 2nd is always coming in as organic. As far as I can tell, there is nothing different in the settings of the devices.  Is there a device setting that would be preventing the SDK recognizing the tracker from the link that was clicked?

Thanks!

**Comment by uerceg** [comment]
Deferred deep linking is scenario which happens **in install scenario only**. So literally only when your user installs your app for the very first time (install in Adjust sense which for us means we are seeing incoming session package for the first time ever for this user for this app).

So that callback you're setting (deferred deep link callback) is will only be fired in that moment after install when our SDK receives deferred deep link from backend. In order to recreate this scenario, you need to perform following steps:

1. Uninstall your app from test device.
2. Forget your test device from our testing console in Adjust dashboard (this makes our backend to completely forget your device's data and next time you start SDK and it sends session package to our backend, that will be treated as install scenario).
3. Click on your tracker URL where you placed content of deep link you want to get deferredly.
4. Start your app and launch SDK.

In this scenario, you should see deferred deep link callback being fired. In this and none other unless you repeat the flow from above.

Does this answer your doubts maybe?

**Comment by uerceg** [comment]
In this particular case from above - nope. You did remove your app, but device is still known to us and this is why you see this session too frequent error being fired upon session tracking. 

Try taking your current idfa value (3FDBC149-2706-4414-B54D-97DE2F700E8E), go to testing console and forget the device with it. Uninstall an app and then rerun it (of course, click on tracker URL prior to install). It should do the trick.

**Comment by ericpolkadoc** [comment]
ok -- I was resetting the Advertising Id on the device thinking that your servers would see it as a new device, which I now see is not the case.  In manually removing it I was able to see the deeplink!

I also have a similar issue with Android, in that the tracker found on install is always organic.  I know I've been manually removing the id from my testing console, and I've been using the Adjust Insights app to make sure I am using the correct Id.  

In this example, the Adjust Insights app says my Advertising Id is 

3e1ef164-84cc-48d7-9790-c0e32a50a12d

but in the logs, it looks like the SDK is seeing Adid =  e781f3f00d37635e7bff0d6327e45a5f? 

Is there a recommend way to test deep links on Android without using Slack?

Here's my Android log, please let me know if you see something I am not.

Thanks!

05-26 08:06:53.505	com...	18570	-	W	Adjust  	 SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!	
05-26 08:06:53.506	com...	18570	-	W	Adjust  	 SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!	
05-26 08:06:53.511	com...	18570	18685	D	Adjust  	 adjust_config.properties file not found in this app	
05-26 08:06:53.517	system_server	24159	24346	V	WindowManager	 Relayout 18018: mAttrs={(0,0)(wrapxwrap) sim={adjust=pan forwardNavigation} ty=BASE_APPLICATION fmt=TRANSLUCENT surfaceInsets=Rect(6, 6 - 6, 6)	
05-26 08:06:53.530	system_server	24159	27034	V	WindowManager	 Relayout 18018: mAttrs={(0,0)(wrapxwrap) sim={adjust=pan} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x10302f5 surfaceInsets=Rect(6, 6 - 6, 6)	
05-26 08:06:53.543	system_server	24159	27034	V	WindowManager	 Relayout 24100: mAttrs={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030305 sysuil=true	
05-26 08:06:53.934	system_server	24159	24346	V	WindowManager	 Relayout 18570: mAttrs={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} layoutInDisplayCutoutMode=always ty=BASE_APPLICATION wanim=0x1030305	
05-26 08:06:53.986	system_server	24159	24183	V	InputMethodManagerService	 startInputOrWindowGainedFocusInternalLocked: reason=WINDOW_FOCUS_GAIN client=android.os.BinderProxy@320e5de inputContext=null missingMethods= attribute=android.view.inputmethod.EditorInfo@57ce416 startInputFlags=FIRST_WINDOW_FOCUS_GAIN|INITIAL_CONNECTION softInputMode=STATE_UNSPECIFIED|ADJUST_PAN|IS_FORWARD_NAVIGATION windowFlags=#81810100 unverifiedTargetSdkVersion=29	
05-26 08:06:54.256	system_server	24159	24183	V	InputMethodManagerService	 startInputOrWindowGainedFocusInternalLocked: reason=CHECK_FOCUS client=android.os.BinderProxy@320e5de inputContext=null missingMethods= attribute=android.view.inputmethod.EditorInfo@94c467f startInputFlags=VIEW_HAS_FOCUS|INITIAL_CONNECTION softInputMode=STATE_UNSPECIFIED|ADJUST_PAN windowFlags=#81810100 unverifiedTargetSdkVersion=29	
05-26 08:06:54.408	system_server	24159	24346	V	WindowManager	 Relayout 18570: mAttrs={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} layoutInDisplayCutoutMode=always ty=BASE_APPLICATION wanim=0x1030305	
05-26 08:06:54.470	system_server	24159	30640	V	InputMethodManagerService	 startInputOrWindowGainedFocusInternalLocked: reason=WINDOW_FOCUS_GAIN client=android.os.BinderProxy@320e5de inputContext=null missingMethods= attribute=android.view.inputmethod.EditorInfo@a0b7fb0 startInputFlags=FIRST_WINDOW_FOCUS_GAIN|INITIAL_CONNECTION softInputMode=STATE_UNSPECIFIED|ADJUST_PAN|IS_FORWARD_NAVIGATION windowFlags=#81810180 unverifiedTargetSdkVersion=29	
05-26 08:06:55.549	com...	18570	-	I	TiAPI   	  [AdjustExample]: Session tracking succeeded callback invoked!	
05-26 08:06:55.549	com...	18570	-	I	TiAPI   	  [AdjustExample]: Message: Install tracked	
05-26 08:06:55.549	com...	18570	-	I	TiAPI   	  [AdjustExample]: Timestamp: 2020-05-26T15:06:52.421Z+0000	
05-26 08:06:55.549	com...	18570	-	I	TiAPI   	  [AdjustExample]: Adid: e781f3f00d37635e7bff0d6327e45a5f	
05-26 08:06:55.549	com...	18570	-	I	TiAPI   	  [AdjustExample]: JSON response: {"app_token":"...","adid":"e781f3f00d37635e7bff0d6327e45a5f","timestamp":"2020-05-26T15:06:52.421Z+0000","message":"Install tracked","ask_in":2000}	
05-26 08:06:55.560	system_server	24159	30640	V	WindowManager	 Relayout 18570: mAttrs={(0,0)(fillxfill) sim={adjust=pan forwardNavigation} layoutInDisplayCutoutMode=always ty=BASE_APPLICATION wanim=0x1030305	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Attribution callback invoked!	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Tracker token = ei4a2ka	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Tracker name = Organic	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Network = Organic	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Campaign = 	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Adgroup = 	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Creative = 	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Click label = 	
05-26 08:06:58.268	com...	18570	-	I	TiAPI   	  [AdjustExample]: Adid = e781f3f00d37635e7bff0d6327e45a5f

**Comment by uerceg** [comment]
`adid` is Adjust internal identifier for the device. What you read for your Google Advertising Id is probably correct value. When it comes to attributing install to a click, that depends from several factors. This is list you can check:

- First question is how does your tracker URL which you're clicking onto look like. Does it contain your device identifier in the URL (&gps_adid=3e1ef164-84cc-48d7-9790-c0e32a50a12d) or not?
- If it contains `gps_adid` parameter in the URL, it should work.
- If it doesn't contain `gps_adid` parameter, then in order to attribute click to install fingerprinting needs to take place.
- If attribution is not happening in fingerprinting scenario, you should be aware that since a while ago each new tracker which is created in Adjust dashboard has fingerprinting for attributing clicks to installs OFF by default. You should probably go to dashboard and check tracker whose token you're using in tracker URL and see if it has fingerprinting for clicks enabled. If not, enable it and retry, it should work then.

**Comment by ericpolkadoc** [comment]
Wow -- the fingerprinting setting to ON did the trick for my Android issue.  Hopefully this squares everything away for me.

I must say you've been incredibly thorough and helpful, thank you!

**Comment by uerceg** [comment]
Good news!

I'll close the issue, but in case you end up with some other problems/questions, feel free to reopen/comment.

Cheers!
