### ISSUE TITLE
Titanium SDK 9.0.2 Google Play Services Issue

### ISSUE THREAD

**Issue by emajoe** [adjust/titanium_sdk#20]
Hello,

The android module cause the app to crash due to a google play services error, `"The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 12451000 but found 10260000. "`

This is using TItanium SDK 9.0.2

**Comment by uerceg** [comment]
Hi @emajoe 

TBH, not sure if it's related to our SDK. Are you following advice to use [ti.playservices](https://github.com/adjust/titanium_sdk#android-gps) for dependency we need to access Google Advertising Id? If yes, why are you having line which says something like this:

```xml
<meta-data
    android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
```

in your `AndroidManifest.xml` and if yes, do you know the reason why and why it might be pointing to version `10260000`?

**Comment by emajoe** [comment]
Hello,  

Yes even with ti.playservices setup that error occurs. Looks like its here https://github.com/adjust/titanium_sdk/blob/master/android/android/platform/android/res/values/version.xml

**Comment by emajoe** [comment]
Changing that value to 12451000 worked and the app runs correctly now.

**Comment by uerceg** [comment]
Great! Yeah I would imagine that maybe initially it got set to first number you saw and maybe ti.playservices got updated in between but somehow version number in that location didn't. Not really sure TBH. But great news that it works now! In case you have any further question(s), feel free to ping.

Cheers
