### ISSUE TITLE
iOS 14 update

### ISSUE THREAD

**Issue by ericpolkadoc** [adjust/titanium_sdk#21]
Hi,

Are there plans to update the Titanium SDK with the new Adjust SDK supporting iOS14?

Thanks,
Eric

**Comment by ugi** [comment]
Hi @ericpolkadoc 

We just added support to our latest [v4.23.0](https://github.com/adjust/titanium_sdk/releases/tag/v4.23.0) update. Feel free to give it a shot and comment/reopen in case you encounter any issues.

Cheers
