### ISSUE TITLE
Titanium released v7.0 Suppor

### ISSUE THREAD

**Issue by amigoni** [adjust/titanium_sdk#7]
Titanium release v7.0 which addresses Android JAR and AAR build conflicts. Any chance to get a release for that ASAP. We are currently blocked from releasing due to JAR conflicts with other modules.

**Comment by uerceg** [comment]
Hi @amigoni

Titanium SDK update was planned to be out until the end of the year. Can you share some more insigts about this error (explanation what is happening or some link to the issue)?

**Comment by uerceg** [comment]
@amigoni 

Also, which IDE and which IDE version are you using for your Titanium development?

**Comment by amigoni** [comment]
Hi Ugi,
Due to various conflict between various modules .jar's for android we want
to move to SDK 7.0 ASAP as it fully support multidex and would take care of
the vast majority of our current build issues with Android. I am going
through all the modules we are using and pinging the developer to see if
they can help making the transition easier. I realize currently it's not
per se your issue but modules not playing nice with eachother is a huge
issue for us and SDK 7.0 will solve most of those.

Leo Amigoni

**Comment by uerceg** [comment]
@amigoni 

We have pushed Titanium SDK update a bit up in our priority list and we started to work on it, but will take us a bit to update.

I am still unsure what the issue really is? Is there some issue with Adjust Titanium plugin once you tried to build your app with our SDK inside of it with newest Titanium SDK 7.0.0? If yes, what is the exact error? Or did you just see our SDK conflicting with some of your plugins when trying to build your app on pre Titanium SDK 7.0.0? And of course, if yes, how does the error look like?

Thanks in advance for any further clarifications.

**Comment by amigoni** [comment]
The issue is that the module is not even selectable to build for 7.0 on
Android

Leo Amigoni

**Comment by uerceg** [comment]
Thanks for the explanation, will be checked. Will keep you posted in here about progress.

**Comment by amigoni** [comment]
Hi, any news on this one, we are currently help back from upgrading. Thanks

**Comment by uerceg** [comment]
Hi @amigoni 

This week we have finished with native iOS updates and next one is aimed for some updates on native Android side after which we are going to proceed with non natives update. We don't really work with some hard ETAs but I hope that in around two weeks we will update Titanium SDK and we are aiming to make it Titanium 7.0+ compatible.

**Comment by uerceg** [comment]
Hi @amigoni 

Titanium SDK v4.12.0 with Titanium 7.0.0+ support is live: https://github.com/adjust/titanium_sdk/releases/tag/v4.12.0

Feel free to give it a try and to reopen this issue if you still face the same problems.

Cheers
