### ISSUE TITLE
Conflict with outdated Jar files below 7.0 and Ti.Map

### ISSUE THREAD

**Issue by amigoni** [adjust/titanium_sdk#8]
I'm having an issue I haven't been able to resolve for days. The combination of Ti.Map and Ti.goosh with SDK 6.2 or greater. I can't seem to find a way to use proguard to build the proper files as the google-play-services.jar files with everything in it are not available for the newer versions. I tried to delete the .jar files in ti.goosh that would conflict with Ti.Map. Leaving only: gsm, iid, tasks jars but still I get an error.
[ERROR] :  V8Exception: Exception occurred at /app.js:740: Uncaught Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
[ERROR] :  V8Exception: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;

Does anyone know how to solve this? I have been at it for over a week now and no luck. Thanks so much in advance. As soon as all my modules upgrade to 7.0 support hopefully this jar nightmare will be done for good. 

Thanks

**Comment by uerceg** [comment]
@amigoni

We will try to reproduce the issue with these plugins you mentioned. However, Google Play Services library (and to be more precise in Adjust context - it’s analytics (or basement) part) is not something what our plugin think of as a must to exist within itself. In our README, we have explained that: https://github.com/adjust/titanium_sdk/blob/master/README.md#android-gps

Read what is written in that chapter and feel free to remove Google Play Services from our module if some other module is already including it. If gps_adid parameter is present in your sessions/events afterwards, we are perfectly fine with Google Play Services not existing in your app as part of our SDK. 

But then again, if removed and you still see these issues, not sure how much does it have to do with our plugin anymore.

**Comment by amigoni** [comment]
Thanks Ugi,
Yeah I know I don't think it's per se your issue. Mostly the implementation
for Titanium. I did exactly that, remove play services for v 6.x and it
works but for v 7.0 your module must not be supported as it's not
selectable.

Leo Amigoni

**Comment by uerceg** [comment]
Gotcha. :+1: Will be investigated and upcoming v4.12.0 update will be made to be 7.0.0 compatible.

**Comment by amigoni** [comment]
Thank you very much. Happy holidays.

Leo Amigoni

**Comment by uerceg** [comment]
Hi @amigoni 

Titanium SDK v4.12.0 with Titanium 7.0.0+ support is live: https://github.com/adjust/titanium_sdk/releases/tag/v4.12.0

Feel free to give it a try and to reopen this issue if you still face the same problems.

Cheers
