### ISSUE TITLE
v4.1.11  getGoogleAdId returns null

### ISSUE THREAD

**Issue by amigoni** [adjust/titanium_sdk#9]
Titanium SDK 6.3.0, Android getGoogleAdId returns always null. Going to try it out with 4.1.12

**Comment by uerceg** [comment]
Hi @amigoni 

When you track event while testing, do you see parameter called `gps_adid` being tracked?

**Comment by amigoni** [comment]
I'm not sure I understand the question. I don't use event tracking for your
module, we use our own.

Leo Amigoni

**Comment by uerceg** [comment]
@amigoni 

Dod you manage to read Google Play Advertising Identifier with this method or do you still face this issue?

**Comment by uerceg** [comment]
Closing this one due to inactivity, feel free to reopen it in case issue still persists with our latest SDK release.
